server:
  port: 8080
  application:
    name: game-server
  servlet:
    context-path: /server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wordgame&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000




mybatis-plus:
  mapper-locations: classpath:**/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true